meta:
  engine: 4.0.5
  name: ergogen-footprints-demo
  version: 0.1
  ref: &kb_ref "Ergogen Footprints Demo v0.1 (by ceoloide)"
  url: &kb_url "https://github.com/ceoloide/ergogen-footprints"
units:  
  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
points:
  zones:
    board_center:
      anchor:
        shift: [75, -75] # Fix KiCad placement
      key:
        tags:
          - helper
    choc_v1_v2:
      key:
        padding: 20
        spread: 20
        tags:
          - key
      anchor:
        - ref: board_center
          shift: [-40,-40]
      columns:
        c1:
        c2:
        c3:
      # Rows are populated bottom-to-top, so we invert the order to have
      # top-to-bottom
      rows:
        r5: 
        r4:
        r3:
        r2:
        r1:


outlines:
  board_outline:
    - what: rectangle
      where: /board_center/
      size: [99.5,99.5]
      fillet: fillet_radius
  preview:
    - what: outline
      name: board_outline
    - what: rectangle
      where: /key/
      size: [6,0.01]
      operation: stack
    - what: rectangle
      where: /key/
      size: [0.01,4]
      operation: stack
    - what: rectangle
      size: [20,20]
      where: /key/
      operation: stack

pcbs:
  ergogen_footprints_demo:
    outlines:
      main:
        outline: board_outline
    footprints:
      switch_1_1:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c1_r1]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          solder: false
          include_stabilizer_pad: true
          oval_stabilizer_pad: false
          choc_v1_support: false
          choc_v2_support: true
          outer_pad_width_back: 1.6
        adjust:
          rotate: 180
      switch_1_2:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c1_r2]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          solder: false
          include_stabilizer_pad: true
          oval_stabilizer_pad: true
          choc_v1_support: false
          choc_v2_support: true
          outer_pad_width_back: 1.6
        adjust:
          rotate: 180
      switch_1_3:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c1_r3]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          solder: false
          choc_v1_support: true
          choc_v2_support: false
          outer_pad_width_back: 1.6
        adjust:
          rotate: 180
      switch_1_4:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c1_r4]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          solder: false
          choc_v1_support: true
          choc_v2_support: true
          outer_pad_width_back: 1.6
        adjust:
          rotate: 180
      switch_1_5:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c1_r5]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          solder: true
          choc_v1_support: false
          choc_v2_support: true
          oval_stabilizer_pad: true
          outer_pad_width_back: 1.6
        adjust:
          rotate: 180
      switch_2_1:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c2_r1]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: false
          solder: true
          include_stabilizer_pad: true
          oval_stabilizer_pad: false
          choc_v1_support: false
          choc_v2_support: true
        adjust:
          rotate: 180
      switch_2_2:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c2_r2]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: false
          solder: true
          include_stabilizer_pad: true
          oval_stabilizer_pad: true
          choc_v1_support: false
          choc_v2_support: true
        adjust:
          rotate: 180
      switch_2_3:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c2_r3]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: false
          solder: true
          include_stabilizer_pad: true
          oval_stabilizer_pad: true
          choc_v1_support: true
          choc_v2_support: false
        adjust:
          rotate: 180
      switch_2_4:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c2_r4]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: false
          solder: true
          include_stabilizer_pad: true
          oval_stabilizer_pad: false
          choc_v1_support: true
          choc_v2_support: true
        adjust:
          rotate: 180
      switch_2_5:
        what: ceoloide/switch_choc_v1_v2
        where: [choc_v1_v2_c2_r5]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          solder: true
          choc_v1_support: false
          choc_v2_support: true
          oval_stabilizer_pad: false
          outer_pad_width_back: 1.6
        adjust:
          rotate: 180

      diodes_b:
        what: ceoloide/diode_tht_sod123
        where: [/choc_v1_v2_c1_.*/, /choc_v1_v2_c2_.*/]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: B
        adjust:
          rotate: -90
          shift: [-7.75,1]

      diodes_f:
        what: ceoloide/diode_tht_sod123
        where: [/choc_v1_v2_c1/, /choc_v1_v2_c2/]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: F
        adjust:
          rotate: -90
          shift: [8.25,1]

      battery_connector_1:
        what: ceoloide/battery_connector_jst_ph_2
        where: board_center
        params:
          reversible: true
          include_traces: true
        adjust:
          shift: [25,-40]
          rotate: 45

      mounting_hole_1:
        what: ceoloide/mounting_hole_npth
        where: board_center
        params:
          hole_size: spacer_diameter
          hole_drill: spacer_diameter

      screw_hole_1:
        what: ceoloide/mounting_hole_npth
        where: board_center
        params:
          hole_size: screw_diameter
          hole_drill: screw_diameter

      power_switch_smd_1:
        what: ceoloide/power_switch_smd_side
        where: board_center
        params:
          reversible: true
          invert_behavior: true

      power_switch_smd_2:
        what: ceoloide/power_switch_smd_side
        where: board_center
        params:
          reversible: true
          invert_behavior: false

      reset_switch_smd_1:
        what: ceoloide/reset_switch_smd_side
        where: board_center
        params:
          reversible: true
          include_bosses: true

      reset_switch_smd_2:
        what: ceoloide/reset_switch_smd_side
        where: board_center
        params:
          reversible: true
          include_bosses: false

      reset_switch_tht_1:
        what: ceoloide/reset_switch_tht_top
        where: board_center
        params:
          reversible: true

      trrs_1:
        what: ceoloide/trrs_pj320a
        where: board_center
        params:
          A: DAT # Tip and first ring can be together
          C: GND
          D: VCC
          reversible: true
          symmetric: false
        adjust:
          shift: [40,20]
          rotate: 45

      trrs_2:
        what: ceoloide/trrs_pj320a
        where: board_center
        params:
          A: DAT # Tip and first ring can be together
          C: GND
          D: VCC
          reversible: true
          symmetric: true
        adjust:
          shift: [50,30]
          rotate: 45

      trrs_3:
        what: ceoloide/trrs_pj320a
        where: board_center
        params:
          A: DAT # Tip and first ring can be together
          C: GND
          D: VCC
          reversible: false
        adjust:
          shift: [60,40]
          rotate: 45
          
      per_key_led_1:
        what: ceoloide/led_sk6812mini-e
        where: choc_v1_v2_c2_r2
        params:
          P1: VCC
          P2: LED_U_1 # DOUT
          P3: GND
          P4: LED_1 # DIN
          side: B
          reversible: false
          reverse_mount: true
        adjust:
          shift: [0, 4.7]
          
      per_key_led_2:
        what: ceoloide/led_sk6812mini-e
        where: choc_v1_v2_c2_r3
        params:
          P1: VCC
          P2: LED_1 # DOUT
          P3: GND
          P4: LED # DIN
          reversible: true
          reverse_mount: true
          include_traces_vias: true
        adjust:
          shift: [0, 4.7]
      
      underglow_led_1:
        what: ceoloide/led_sk6812mini-e
        where: choc_v1_v2_c1_r3
        params:
          P1: VCC
          P2: LED_U_2 # DOUT
          P3: GND
          P4: LED_U_1 # DIN
          reversible: true
          reverse_mount: false
          include_traces_vias: true
        adjust:
          shift: [0, 4.7]
      
      underglow_led_2:
        what: ceoloide/led_sk6812mini-e
        where: choc_v1_v2_c1_r1
        params:
          P1: VCC
          P2: LED_U_3 #DOUT
          P3: GND
          P4: LED_U_2 #DIN
          side: B
          reversible: false
          reverse_mount: false
        adjust:
          shift: [0, 4.7]
      
      jlcpcb_order_number_text:
        what: ceoloide/text
        where: board_center
        params:
          text: JLCJLCJLCJLC
          reversible: true
        adjust:
          shift: [0,40]
          rotate: 45

      nice_nano_1:
        what: ceoloide/nice_nano
        where: board_center
        params:
          use_rectangular_jumpers: false
        adjust:
            shift: [25,0]
            rotate: 45

      nice_nano_2:
        what: ceoloide/nice_nano
        where: board_center
        params:
          use_rectangular_jumpers: true
        adjust:
          shift: [50,0]
          rotate: 45
      
      nice_view_1:
        what: ceoloide/nice_view
        where: board_center
        params:
          MOSI: SDA
          SCK: SCL
          reversible: true
          invert_jumpers_position: false
        adjust:
          shift: [25,25]
          rotate: 45
      
      nice_view_2:
        what: ceoloide/nice_view
        where: board_center
        params:
          MOSI: SDA
          SCK: SCL
          reversible: true
          invert_jumpers_position: true
        adjust:
          shift: [50,25]
          rotate: 45
      
      ssd1306_nice_view_1:
        what: ceoloide/display_ssd1306_nice_view
        where: board_center
        params:
          reversible: true
          display_type: ssd1306
      
      ssd1306_nice_view_2:
        what: ceoloide/display_ssd1306_nice_view
        where: board_center
        params:
          reversible: true
          display_type: nice_view
      
      ssd1306_nice_view_3:
        what: ceoloide/display_ssd1306_nice_view
        where: board_center
        params:
          reversible: true
          display_type: both
      
